/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R3plLosAngelesRouteImport } from './routes/3pl-los-angeles'
import { Route as AmazonFbaPrepRouteImport } from './routes/amazon-fba-prep'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as InventoryManagementRouteImport } from './routes/inventory-management'
import { Route as KittingBundlingRouteImport } from './routes/kitting-bundling'
import { Route as LabelingFnskuRouteImport } from './routes/labeling-fnsku'
import { Route as LaunchpadRouteImport } from './routes/launchpad'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OrderFulfillmentRouteImport } from './routes/order-fulfillment'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReceivingInspectionRouteImport } from './routes/receiving-inspection'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReturnsProcessingRouteImport } from './routes/returns-processing'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ShopifyFulfillmentRouteImport } from './routes/shopify-fulfillment'
import { Route as StorageWarehousingRouteImport } from './routes/storage-warehousing'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as TiktokShopFulfillmentRouteImport } from './routes/tiktok-shop-fulfillment'
import { Route as WalmartFulfillmentRouteImport } from './routes/walmart-fulfillment'
import { Route as WestCoastFulfillmentRouteImport } from './routes/west-coast-fulfillment'
import { Route as WhyChooseUsRouteImport } from './routes/why-choose-us'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ClientDashboardRouteImport } from './routes/client/dashboard'
import { Route as ClientSettingsRouteImport } from './routes/client/settings'
import { Route as PlatformsIndexRouteImport } from './routes/platforms/index'
import { Route as PlatformsSplatRouteImport } from './routes/platforms/$'
import { Route as SalesChannelsIndexRouteImport } from './routes/sales-channels/index'
import { Route as SalesChannelsAmazonRouteImport } from './routes/sales-channels/amazon'
import { Route as SalesChannelsShopifyRouteImport } from './routes/sales-channels/shopify'
import { Route as SalesChannelsTiktokShopRouteImport } from './routes/sales-channels/tiktok-shop'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R3plLosAngelesRoute = R3plLosAngelesRouteImport.update({
  id: '/3pl-los-angeles',
  path: '/3pl-los-angeles',
  getParentRoute: () => rootRouteImport,
} as any)
const AmazonFbaPrepRoute = AmazonFbaPrepRouteImport.update({
  id: '/amazon-fba-prep',
  path: '/amazon-fba-prep',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryManagementRoute = InventoryManagementRouteImport.update({
  id: '/inventory-management',
  path: '/inventory-management',
  getParentRoute: () => rootRouteImport,
} as any)
const KittingBundlingRoute = KittingBundlingRouteImport.update({
  id: '/kitting-bundling',
  path: '/kitting-bundling',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelingFnskuRoute = LabelingFnskuRouteImport.update({
  id: '/labeling-fnsku',
  path: '/labeling-fnsku',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchpadRoute = LaunchpadRouteImport.update({
  id: '/launchpad',
  path: '/launchpad',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderFulfillmentRoute = OrderFulfillmentRouteImport.update({
  id: '/order-fulfillment',
  path: '/order-fulfillment',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceivingInspectionRoute = ReceivingInspectionRouteImport.update({
  id: '/receiving-inspection',
  path: '/receiving-inspection',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsProcessingRoute = ReturnsProcessingRouteImport.update({
  id: '/returns-processing',
  path: '/returns-processing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopifyFulfillmentRoute = ShopifyFulfillmentRouteImport.update({
  id: '/shopify-fulfillment',
  path: '/shopify-fulfillment',
  getParentRoute: () => rootRouteImport,
} as any)
const StorageWarehousingRoute = StorageWarehousingRouteImport.update({
  id: '/storage-warehousing',
  path: '/storage-warehousing',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const TiktokShopFulfillmentRoute = TiktokShopFulfillmentRouteImport.update({
  id: '/tiktok-shop-fulfillment',
  path: '/tiktok-shop-fulfillment',
  getParentRoute: () => rootRouteImport,
} as any)
const WalmartFulfillmentRoute = WalmartFulfillmentRouteImport.update({
  id: '/walmart-fulfillment',
  path: '/walmart-fulfillment',
  getParentRoute: () => rootRouteImport,
} as any)
const WestCoastFulfillmentRoute = WestCoastFulfillmentRouteImport.update({
  id: '/west-coast-fulfillment',
  path: '/west-coast-fulfillment',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyChooseUsRoute = WhyChooseUsRouteImport.update({
  id: '/why-choose-us',
  path: '/why-choose-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/client/dashboard',
  path: '/client/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientSettingsRoute = ClientSettingsRouteImport.update({
  id: '/client/settings',
  path: '/client/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformsIndexRoute = PlatformsIndexRouteImport.update({
  id: '/platforms/',
  path: '/platforms/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformsSplatRoute = PlatformsSplatRouteImport.update({
  id: '/platforms/$',
  path: '/platforms/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesChannelsIndexRoute = SalesChannelsIndexRouteImport.update({
  id: '/sales-channels/',
  path: '/sales-channels/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesChannelsAmazonRoute = SalesChannelsAmazonRouteImport.update({
  id: '/sales-channels/amazon',
  path: '/sales-channels/amazon',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesChannelsShopifyRoute = SalesChannelsShopifyRouteImport.update({
  id: '/sales-channels/shopify',
  path: '/sales-channels/shopify',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesChannelsTiktokShopRoute = SalesChannelsTiktokShopRouteImport.update({
  id: '/sales-channels/tiktok-shop',
  path: '/sales-channels/tiktok-shop',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/3pl-los-angeles': typeof R3plLosAngelesRoute
  '/amazon-fba-prep': typeof AmazonFbaPrepRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory-management': typeof InventoryManagementRoute
  '/kitting-bundling': typeof KittingBundlingRoute
  '/labeling-fnsku': typeof LabelingFnskuRoute
  '/launchpad': typeof LaunchpadRoute
  '/login': typeof LoginRoute
  '/order-fulfillment': typeof OrderFulfillmentRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/receiving-inspection': typeof ReceivingInspectionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns-processing': typeof ReturnsProcessingRoute
  '/services': typeof ServicesRoute
  '/shopify-fulfillment': typeof ShopifyFulfillmentRoute
  '/storage-warehousing': typeof StorageWarehousingRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/tiktok-shop-fulfillment': typeof TiktokShopFulfillmentRoute
  '/walmart-fulfillment': typeof WalmartFulfillmentRoute
  '/west-coast-fulfillment': typeof WestCoastFulfillmentRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/settings': typeof ClientSettingsRoute
  '/platforms/$': typeof PlatformsSplatRoute
  '/sales-channels/amazon': typeof SalesChannelsAmazonRoute
  '/sales-channels/shopify': typeof SalesChannelsShopifyRoute
  '/sales-channels/tiktok-shop': typeof SalesChannelsTiktokShopRoute
  '/blog/': typeof BlogIndexRoute
  '/platforms/': typeof PlatformsIndexRoute
  '/sales-channels/': typeof SalesChannelsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/3pl-los-angeles': typeof R3plLosAngelesRoute
  '/amazon-fba-prep': typeof AmazonFbaPrepRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory-management': typeof InventoryManagementRoute
  '/kitting-bundling': typeof KittingBundlingRoute
  '/labeling-fnsku': typeof LabelingFnskuRoute
  '/launchpad': typeof LaunchpadRoute
  '/login': typeof LoginRoute
  '/order-fulfillment': typeof OrderFulfillmentRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/receiving-inspection': typeof ReceivingInspectionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns-processing': typeof ReturnsProcessingRoute
  '/services': typeof ServicesRoute
  '/shopify-fulfillment': typeof ShopifyFulfillmentRoute
  '/storage-warehousing': typeof StorageWarehousingRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/tiktok-shop-fulfillment': typeof TiktokShopFulfillmentRoute
  '/walmart-fulfillment': typeof WalmartFulfillmentRoute
  '/west-coast-fulfillment': typeof WestCoastFulfillmentRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/settings': typeof ClientSettingsRoute
  '/platforms/$': typeof PlatformsSplatRoute
  '/sales-channels/amazon': typeof SalesChannelsAmazonRoute
  '/sales-channels/shopify': typeof SalesChannelsShopifyRoute
  '/sales-channels/tiktok-shop': typeof SalesChannelsTiktokShopRoute
  '/blog': typeof BlogIndexRoute
  '/platforms': typeof PlatformsIndexRoute
  '/sales-channels': typeof SalesChannelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/3pl-los-angeles': typeof R3plLosAngelesRoute
  '/amazon-fba-prep': typeof AmazonFbaPrepRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/integrations': typeof IntegrationsRoute
  '/inventory-management': typeof InventoryManagementRoute
  '/kitting-bundling': typeof KittingBundlingRoute
  '/labeling-fnsku': typeof LabelingFnskuRoute
  '/launchpad': typeof LaunchpadRoute
  '/login': typeof LoginRoute
  '/order-fulfillment': typeof OrderFulfillmentRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/receiving-inspection': typeof ReceivingInspectionRoute
  '/reset-password': typeof ResetPasswordRoute
  '/returns-processing': typeof ReturnsProcessingRoute
  '/services': typeof ServicesRoute
  '/shopify-fulfillment': typeof ShopifyFulfillmentRoute
  '/storage-warehousing': typeof StorageWarehousingRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/thank-you': typeof ThankYouRoute
  '/tiktok-shop-fulfillment': typeof TiktokShopFulfillmentRoute
  '/walmart-fulfillment': typeof WalmartFulfillmentRoute
  '/west-coast-fulfillment': typeof WestCoastFulfillmentRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/settings': typeof ClientSettingsRoute
  '/platforms/$': typeof PlatformsSplatRoute
  '/sales-channels/amazon': typeof SalesChannelsAmazonRoute
  '/sales-channels/shopify': typeof SalesChannelsShopifyRoute
  '/sales-channels/tiktok-shop': typeof SalesChannelsTiktokShopRoute
  '/blog/': typeof BlogIndexRoute
  '/platforms/': typeof PlatformsIndexRoute
  '/sales-channels/': typeof SalesChannelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/3pl-los-angeles'
    | '/amazon-fba-prep'
    | '/contact'
    | '/faq'
    | '/integrations'
    | '/inventory-management'
    | '/kitting-bundling'
    | '/labeling-fnsku'
    | '/launchpad'
    | '/login'
    | '/order-fulfillment'
    | '/pricing'
    | '/privacy'
    | '/receiving-inspection'
    | '/reset-password'
    | '/returns-processing'
    | '/services'
    | '/shopify-fulfillment'
    | '/storage-warehousing'
    | '/terms'
    | '/testimonials'
    | '/thank-you'
    | '/tiktok-shop-fulfillment'
    | '/walmart-fulfillment'
    | '/west-coast-fulfillment'
    | '/why-choose-us'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/blog/$slug'
    | '/client/dashboard'
    | '/client/settings'
    | '/platforms/$'
    | '/sales-channels/amazon'
    | '/sales-channels/shopify'
    | '/sales-channels/tiktok-shop'
    | '/blog/'
    | '/platforms/'
    | '/sales-channels/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/3pl-los-angeles'
    | '/amazon-fba-prep'
    | '/contact'
    | '/faq'
    | '/integrations'
    | '/inventory-management'
    | '/kitting-bundling'
    | '/labeling-fnsku'
    | '/launchpad'
    | '/login'
    | '/order-fulfillment'
    | '/pricing'
    | '/privacy'
    | '/receiving-inspection'
    | '/reset-password'
    | '/returns-processing'
    | '/services'
    | '/shopify-fulfillment'
    | '/storage-warehousing'
    | '/terms'
    | '/testimonials'
    | '/thank-you'
    | '/tiktok-shop-fulfillment'
    | '/walmart-fulfillment'
    | '/west-coast-fulfillment'
    | '/why-choose-us'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/blog/$slug'
    | '/client/dashboard'
    | '/client/settings'
    | '/platforms/$'
    | '/sales-channels/amazon'
    | '/sales-channels/shopify'
    | '/sales-channels/tiktok-shop'
    | '/blog'
    | '/platforms'
    | '/sales-channels'
  id:
    | '__root__'
    | '/'
    | '/3pl-los-angeles'
    | '/amazon-fba-prep'
    | '/contact'
    | '/faq'
    | '/integrations'
    | '/inventory-management'
    | '/kitting-bundling'
    | '/labeling-fnsku'
    | '/launchpad'
    | '/login'
    | '/order-fulfillment'
    | '/pricing'
    | '/privacy'
    | '/receiving-inspection'
    | '/reset-password'
    | '/returns-processing'
    | '/services'
    | '/shopify-fulfillment'
    | '/storage-warehousing'
    | '/terms'
    | '/testimonials'
    | '/thank-you'
    | '/tiktok-shop-fulfillment'
    | '/walmart-fulfillment'
    | '/west-coast-fulfillment'
    | '/why-choose-us'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/blog/$slug'
    | '/client/dashboard'
    | '/client/settings'
    | '/platforms/$'
    | '/sales-channels/amazon'
    | '/sales-channels/shopify'
    | '/sales-channels/tiktok-shop'
    | '/blog/'
    | '/platforms/'
    | '/sales-channels/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R3plLosAngelesRoute: typeof R3plLosAngelesRoute
  AmazonFbaPrepRoute: typeof AmazonFbaPrepRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  IntegrationsRoute: typeof IntegrationsRoute
  InventoryManagementRoute: typeof InventoryManagementRoute
  KittingBundlingRoute: typeof KittingBundlingRoute
  LabelingFnskuRoute: typeof LabelingFnskuRoute
  LaunchpadRoute: typeof LaunchpadRoute
  LoginRoute: typeof LoginRoute
  OrderFulfillmentRoute: typeof OrderFulfillmentRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ReceivingInspectionRoute: typeof ReceivingInspectionRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReturnsProcessingRoute: typeof ReturnsProcessingRoute
  ServicesRoute: typeof ServicesRoute
  ShopifyFulfillmentRoute: typeof ShopifyFulfillmentRoute
  StorageWarehousingRoute: typeof StorageWarehousingRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ThankYouRoute: typeof ThankYouRoute
  TiktokShopFulfillmentRoute: typeof TiktokShopFulfillmentRoute
  WalmartFulfillmentRoute: typeof WalmartFulfillmentRoute
  WestCoastFulfillmentRoute: typeof WestCoastFulfillmentRoute
  WhyChooseUsRoute: typeof WhyChooseUsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientSettingsRoute: typeof ClientSettingsRoute
  PlatformsSplatRoute: typeof PlatformsSplatRoute
  SalesChannelsAmazonRoute: typeof SalesChannelsAmazonRoute
  SalesChannelsShopifyRoute: typeof SalesChannelsShopifyRoute
  SalesChannelsTiktokShopRoute: typeof SalesChannelsTiktokShopRoute
  BlogIndexRoute: typeof BlogIndexRoute
  PlatformsIndexRoute: typeof PlatformsIndexRoute
  SalesChannelsIndexRoute: typeof SalesChannelsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/3pl-los-angeles': {
      id: '/3pl-los-angeles'
      path: '/3pl-los-angeles'
      fullPath: '/3pl-los-angeles'
      preLoaderRoute: typeof R3plLosAngelesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amazon-fba-prep': {
      id: '/amazon-fba-prep'
      path: '/amazon-fba-prep'
      fullPath: '/amazon-fba-prep'
      preLoaderRoute: typeof AmazonFbaPrepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory-management': {
      id: '/inventory-management'
      path: '/inventory-management'
      fullPath: '/inventory-management'
      preLoaderRoute: typeof InventoryManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitting-bundling': {
      id: '/kitting-bundling'
      path: '/kitting-bundling'
      fullPath: '/kitting-bundling'
      preLoaderRoute: typeof KittingBundlingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labeling-fnsku': {
      id: '/labeling-fnsku'
      path: '/labeling-fnsku'
      fullPath: '/labeling-fnsku'
      preLoaderRoute: typeof LabelingFnskuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launchpad': {
      id: '/launchpad'
      path: '/launchpad'
      fullPath: '/launchpad'
      preLoaderRoute: typeof LaunchpadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-fulfillment': {
      id: '/order-fulfillment'
      path: '/order-fulfillment'
      fullPath: '/order-fulfillment'
      preLoaderRoute: typeof OrderFulfillmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receiving-inspection': {
      id: '/receiving-inspection'
      path: '/receiving-inspection'
      fullPath: '/receiving-inspection'
      preLoaderRoute: typeof ReceivingInspectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns-processing': {
      id: '/returns-processing'
      path: '/returns-processing'
      fullPath: '/returns-processing'
      preLoaderRoute: typeof ReturnsProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopify-fulfillment': {
      id: '/shopify-fulfillment'
      path: '/shopify-fulfillment'
      fullPath: '/shopify-fulfillment'
      preLoaderRoute: typeof ShopifyFulfillmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/storage-warehousing': {
      id: '/storage-warehousing'
      path: '/storage-warehousing'
      fullPath: '/storage-warehousing'
      preLoaderRoute: typeof StorageWarehousingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiktok-shop-fulfillment': {
      id: '/tiktok-shop-fulfillment'
      path: '/tiktok-shop-fulfillment'
      fullPath: '/tiktok-shop-fulfillment'
      preLoaderRoute: typeof TiktokShopFulfillmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/walmart-fulfillment': {
      id: '/walmart-fulfillment'
      path: '/walmart-fulfillment'
      fullPath: '/walmart-fulfillment'
      preLoaderRoute: typeof WalmartFulfillmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/west-coast-fulfillment': {
      id: '/west-coast-fulfillment'
      path: '/west-coast-fulfillment'
      fullPath: '/west-coast-fulfillment'
      preLoaderRoute: typeof WestCoastFulfillmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-choose-us': {
      id: '/why-choose-us'
      path: '/why-choose-us'
      fullPath: '/why-choose-us'
      preLoaderRoute: typeof WhyChooseUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/client/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/settings': {
      id: '/client/settings'
      path: '/client/settings'
      fullPath: '/client/settings'
      preLoaderRoute: typeof ClientSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platforms/': {
      id: '/platforms/'
      path: '/platforms'
      fullPath: '/platforms/'
      preLoaderRoute: typeof PlatformsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platforms/$': {
      id: '/platforms/$'
      path: '/platforms/$'
      fullPath: '/platforms/$'
      preLoaderRoute: typeof PlatformsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-channels/': {
      id: '/sales-channels/'
      path: '/sales-channels'
      fullPath: '/sales-channels/'
      preLoaderRoute: typeof SalesChannelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-channels/amazon': {
      id: '/sales-channels/amazon'
      path: '/sales-channels/amazon'
      fullPath: '/sales-channels/amazon'
      preLoaderRoute: typeof SalesChannelsAmazonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-channels/shopify': {
      id: '/sales-channels/shopify'
      path: '/sales-channels/shopify'
      fullPath: '/sales-channels/shopify'
      preLoaderRoute: typeof SalesChannelsShopifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-channels/tiktok-shop': {
      id: '/sales-channels/tiktok-shop'
      path: '/sales-channels/tiktok-shop'
      fullPath: '/sales-channels/tiktok-shop'
      preLoaderRoute: typeof SalesChannelsTiktokShopRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R3plLosAngelesRoute: R3plLosAngelesRoute,
  AmazonFbaPrepRoute: AmazonFbaPrepRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  IntegrationsRoute: IntegrationsRoute,
  InventoryManagementRoute: InventoryManagementRoute,
  KittingBundlingRoute: KittingBundlingRoute,
  LabelingFnskuRoute: LabelingFnskuRoute,
  LaunchpadRoute: LaunchpadRoute,
  LoginRoute: LoginRoute,
  OrderFulfillmentRoute: OrderFulfillmentRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ReceivingInspectionRoute: ReceivingInspectionRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReturnsProcessingRoute: ReturnsProcessingRoute,
  ServicesRoute: ServicesRoute,
  ShopifyFulfillmentRoute: ShopifyFulfillmentRoute,
  StorageWarehousingRoute: StorageWarehousingRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  ThankYouRoute: ThankYouRoute,
  TiktokShopFulfillmentRoute: TiktokShopFulfillmentRoute,
  WalmartFulfillmentRoute: WalmartFulfillmentRoute,
  WestCoastFulfillmentRoute: WestCoastFulfillmentRoute,
  WhyChooseUsRoute: WhyChooseUsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  BlogSlugRoute: BlogSlugRoute,
  ClientDashboardRoute: ClientDashboardRoute,
  ClientSettingsRoute: ClientSettingsRoute,
  PlatformsSplatRoute: PlatformsSplatRoute,
  SalesChannelsAmazonRoute: SalesChannelsAmazonRoute,
  SalesChannelsShopifyRoute: SalesChannelsShopifyRoute,
  SalesChannelsTiktokShopRoute: SalesChannelsTiktokShopRoute,
  BlogIndexRoute: BlogIndexRoute,
  PlatformsIndexRoute: PlatformsIndexRoute,
  SalesChannelsIndexRoute: SalesChannelsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
